name: Build and test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  buildntest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: make test